DROP SEQUENCE MVCBD_SEQ;
DROP TABLE MVCBOARD;

CREATE SEQUENCE MVCBD_SEQ NOCACHE;

CREATE TABLE MVCBOARD(
	BD_NO NUMBER PRIMARY KEY,
	BD_NAME VARCHAR2(100) NOT NULL,
	BD_TITLE VARCHAR2(200) NOT NULL,
	BD_CONTENT VARCHAR2(4000) NOT NULL,
	BD_DATE DATE NOT NULL
);

INSERT INTO MVCBOARD VALUES(MVCBD_SEQ.NEXTVAL, '이름1','제목 MVC','글 내용 MVC 테스트 중',SYSDATE);

SELECT * FROM MVCBOARD;