DROP TABLE SEOUL_LIB;

CREATE TABLE SEOUL_LIB(
	GU_CODE VARCHAR2(4000),			--위치 구분
	LIB_SEQ NUMBER PRIMARY KEY,		--도서관 번호
	LIB_NAME VARCHAR2(4000),		--도서관명
	ADDR VARCHAR2(4000), 			--주소
	TEL VARCHAR2(4000),				--전화번호
	HPG	VARCHAR2(4000)				--홈페이지 URL
);

SELECT * FROM SEOUL_LIB;