server:
  port: 9000
  
spring:
  application:
    name: user-service
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test;MODE=MySQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    
eureka:
  instance: 
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultzon: http://127.0.0.1:8761/eureka

greeting: hello user service

token:
  expiration_time: 86400000
  secret: user_token