server:
  port: 0
  
spring:
  application:
    name: second-service 
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultzon: http://127.0.0.1:8761/eureka
    