DROP SEQUENCE SEVBD_SEQ;
DROP TABLE SEVBOARD;

CREATE SEQUENCE SEVBD_SEQ NOCACHE;

CREATE TABLE SEVBOARD(
	BD_NO NUMBER PRIMARY KEY,
	BD_NAME VARCHAR2(100) NOT NULL,
	BD_TITLE VARCHAR2(200) NOT NULL,
	BD_CONTENT VARCHAR2(4000) NOT NULL,
	BD_DATE DATE NOT NULL
);

INSERT INTO SEVBOARD VALUES(SEVBD_SEQ.NEXTVAL, '이름1','제목 MVC','글 내용 MVC 테스트 중','2021-01-01');

SELECT * FROM SEVBOARD;