DROP SEQUENCE STSBD_SEQ;
DROP TABLE STSBOARD;

CREATE SEQUENCE STSBD_SEQ NOCACHE;

CREATE TABLE STSBOARD(
	BD_NO NUMBER PRIMARY KEY,
	BD_NAME VARCHAR2(100) NOT NULL,
	BD_TITLE VARCHAR2(200) NOT NULL,
	BD_CONTENT VARCHAR2(4000) NOT NULL,
	BD_DATE DATE NOT NULL
);

INSERT INTO STSBOARD VALUES(STSBD_SEQ.NEXTVAL, '개발자','스프링 MVC 게시판','jsp servlet 그리고 spring',SYSDATE);

SELECT * FROM STSBOARD;

commit;