DROP SEQUENCE BD_SEQ;
DROP TABLE BOARD;

CREATE SEQUENCE BD_SEQ NOCACHE;

CREATE TABLE BOARD(
	BD_NO NUMBER PRIMARY KEY,
	BD_NAME VARCHAR2(100) NOT NULL,
	BD_TITLE VARCHAR2(200) NOT NULL,
	BD_CONTENT VARCHAR2(4000) NOT NULL,
	BD_DATE DATE NOT NULL
);

INSERT INTO BOARD VALUES(BD_SEQ.NEXTVAL, '이름','제목 테스트','글 내용 테스트. 어쩌구 저쩌구. JSP 재미있다. HAHAHA 1234567',SYSDATE);

SELECT * FROM BOARD;