DROP SEQUENCE STSBD_SEQ;
DROP TABLE STSBOARD;

CREATE SEQUENCE STSBD_SEQ NOCACHE;

CREATE TABLE STSBOARD(
    BD_NO NUMBER PRIMARY KEY,
    BD_NAME VARCHAR2(1000) NOT NULL,
    BD_TITLE VARCHAR2(2000) NOT NULL,
    BD_CONTENT VARCHAR2(4000) NOT NULL,
    BD_DATE DATE NOT NULL
);

SELECT * FROM STSBOARD;
