server:
  port: 8001
  
spring:
  application:
    name: first-service
    
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultzon: http://127.0.0.1:8761/eureka
    