spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username:

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true       #sql 보기 좋은 형식으로 변경


logging:
  level:
    org.hibernate.stat: debug
    org.hibernate.type: trace